apiVersion: v1
kind: Namespace
metadata:
  name: mlops
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "mlops_db"
  DB_USER: "mlops_user"
  MINIO_ENDPOINT: "minio-service:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops
type: Opaque
stringData:
  DB_PASSWORD: "mlops_password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
